device = "/dev/input/event2"
master_volume = 1.0
max_voices = 32
samples_dir = "~/.config/keyboard-drums/samples"

# KEY_MUTE
# KEY_VOLUMEDOWN
# KEY_VOLUMEUP
# KEY_PREVIOUSSONG
# KEY_PLAYPAUSE
# KEY_NEXTSONG

[cycling_keys]
next_kit = "KEY_PLAYPAUSE"
#prev_kit = "KEY_LEFT"
next_variant = "KEY_NEXTSONG"
#prev_variant = "KEY_DOWN"

[[bindings]]
key = "KEY_VOLUMEDOWN"
sample = "kick.wav"
gain = 0.8

[[bindings]]
key = "KEY_MUTE"
sample = "snare.wav"
gain = 0.9

[[bindings]]
key = "KEY_VOLUMEUP"
sample = "closed_hat.wav"
gain = 0.8

[[bindings]]
key = "KEY_PREVIOUSSONG"
sample = "open_hat.wav"
gain = 0.8

